version: '3.8'

networks:
  postgres_replica:
    driver: 'bridge'

services:
  db:
    container_name: postgres-1
    image: postgres:15.0
    command: "postgres -c config_file=/config/postgresql.conf"
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "postgresdb"
      PGDATA: "/data"
    volumes:
      - ./pgdata:/data
      - ./config:/config/
      - ./archive:/mnt/server/archive
    ports:
      - 5000:5432
    networks:
      - postgres_replica